[global]
developmentMode = false

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "Space Grotesk"

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
